const F={CO:'CO',O2:'O₂',O:'O',CO2:'CO₂',HC:'C₃H₈',H2O:'H₂O',NO:'NO',N:'N',N2:'N₂'};
const stepNames=['Approach','Stick and activate','Rearrange bonds','Release products'];
const energyNotes=['Reactants begin at the same energy with or without a catalyst.','Temporary bonding to the surface opens a sequence of smaller energy steps.','The highest barrier is lower, so a larger fraction of collisions can react.','Products finish at the same energy, and the metal surface is available again.'];
const R={
co:{name:'Carbon monoxide oxidation',overall:'2 CO + O₂ → 2 CO₂',impact:'Carbon monoxide is a toxic gas. Oxidizing it greatly reduces its acute poisoning hazard.',caveat:'CO₂ is less acutely toxic than CO, but it is still a greenhouse gas.',before:[['CO',2,'pollutant'],['O2',1,'helper']],after:[['CO2',2,'product']],atoms:{C:2,O:4},balance:'Two carbon atoms and four oxygen atoms enter; the same atoms leave in two CO₂ molecules. No metal atom enters the products.',steps:[
{title:'CO and oxygen reach open sites',text:'Two CO molecules and one O₂ molecule move through the exhaust toward open metal sites.',eq:'Reactants are still in the gas phase',gas:[['CO',2],['O2',1]],surf:[],prod:[],status:'Pt / Pd surface: open active sites',chips:['open sites','reactants approaching','no metal consumed'],micro:['CO','O2'],cap:'The microscopic view shows one local encounter; the particle graph keeps the full balanced equation.'},
{title:'Reactants stick and become activated',text:'CO binds temporarily. O₂ also binds and its O–O bond can split, leaving oxygen atoms close to adsorbed CO.',eq:'2 CO* + 2 O* on the surface',gas:[],surf:[['CO*',2],['O*',2]],prod:[],status:'Surface occupied: CO and O are temporarily bound',chips:['adsorbing','splitting O₂','holding reactants close','weakening bonds'],micro:['CO*','O*','O*'],cap:'Dashed lines mean temporary surface interactions. An asterisk (*) means adsorbed.'},
{title:'New C–O bonds form',text:'Each surface oxygen atom joins a CO molecule. The lower-barrier pathway makes CO₂ formation much more likely.',eq:'2 CO* + 2 O* → 2 CO₂*',gas:[],surf:[['CO2*',2]],prod:[],status:'Surface reaction: CO₂ is forming',chips:['lowering the barrier','forming C–O bonds','rearranging existing atoms'],micro:['CO2*','O*'],cap:'The same local event repeats at neighboring sites; the metal does not become part of CO₂.'},
{title:'CO₂ leaves and sites reopen',text:'The CO₂ molecules detach into the exhaust stream. The same sites can begin another cycle.',eq:'2 CO₂* → 2 CO₂ + open sites',gas:[],surf:[],prod:[['CO2',2]],status:'Pt / Pd surface: open again',chips:['desorbing products','regenerating sites','ready to repeat'],micro:['CO2'],cap:'Desorption frees the surface, so the catalyst can be reused.'}]},
hc:{name:'Hydrocarbon oxidation',overall:'C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O',impact:'Unburned hydrocarbons can contribute to ground-level ozone and smog; some are directly toxic.',caveat:'Propane is used here as a simple stand-in for many possible exhaust hydrocarbons.',before:[['HC',1,'pollutant'],['O2',5,'helper']],after:[['CO2',3,'product'],['H2O',4,'product']],atoms:{C:3,H:8,O:10},balance:'All 3 C, 8 H, and 10 O atoms are conserved. The surface helps break and remake bonds; it does not create or destroy atoms.',steps:[
{title:'Unburned fuel and oxygen approach',text:'A propane-like hydrocarbon represents unburned fuel. Five O₂ molecules provide the oxygen needed for complete oxidation.',eq:'C₃H₈ and 5 O₂ in the gas phase',gas:[['HC',1],['O2',5]],surf:[],prod:[],status:'Pt / Pd surface: open active sites',chips:['open sites','fuel approaching','oxygen approaching'],micro:['HC','O2'],cap:'The full reaction involves many atoms; this view shows representative molecules.'},
{title:'Fuel and oxygen bind',text:'The hydrocarbon and oxygen interact temporarily with metal sites. C–H, C–C, and O–O bonds become easier to activate in a sequence of steps.',eq:'C₃H₈* + 10 O* on neighboring sites',gas:[],surf:[['HC*',1],['O*',10]],prod:[],status:'Surface occupied: fuel and oxygen are activated',chips:['adsorbing fuel','activating oxygen','weakening bonds','sharing nearby sites'],micro:['HC*','O*','O*'],cap:'Real hydrocarbon oxidation proceeds through several smaller fragments; the drawing is schematic.'},
{title:'Carbon and hydrogen are oxidized',text:'Existing atoms rearrange: carbon forms CO₂ and hydrogen forms H₂O through a sequence of lower-barrier surface events.',eq:'C fragments → CO₂*; H fragments → H₂O*',gas:[],surf:[['CO2*',3],['H2O*',4]],prod:[],status:'Surface reaction: CO₂ and H₂O are forming',chips:['breaking old bonds','forming C–O bonds','forming O–H bonds','conserving atoms'],micro:['CO2*','H2O*'],cap:'The key idea is a chain of bond-breaking and bond-forming events on neighboring sites.'},
{title:'CO₂ and water leave',text:'Three CO₂ and four H₂O molecules detach. The metal remains in the converter and can process more fuel.',eq:'3 CO₂* + 4 H₂O* → products + open sites',gas:[],surf:[],prod:[['CO2',3],['H2O',4]],status:'Pt / Pd surface: open again',chips:['desorbing products','restoring sites','cycle repeatable'],micro:['CO2','H2O'],cap:'The atom ledger confirms that every carbon, hydrogen, and oxygen atom has a destination.'}]},
nox:{name:'Nitrogen-oxide reduction',overall:'2 NO + 2 CO → N₂ + 2 CO₂',impact:'Nitrogen oxides contribute to smog and can irritate the respiratory system. A three-way catalyst converts much of the nitrogen to N₂.',caveat:'CO serves as the reducing reactant: it removes oxygen from NO while becoming CO₂.',before:[['NO',2,'pollutant'],['CO',2,'helper']],after:[['N2',1,'product'],['CO2',2,'product']],atoms:{N:2,O:4,C:2},balance:'Two nitrogen atoms pair into N₂. Oxygen from NO ends up in CO₂, while the rhodium-containing surface is regenerated.',steps:[
{title:'NO and CO approach rhodium sites',text:'Two NO and two CO molecules move toward open sites. This equation couples reduction of NO with oxidation of CO.',eq:'2 NO + 2 CO in the exhaust gas',gas:[['NO',2],['CO',2]],surf:[],prod:[],status:'Rh-containing surface: open active sites',chips:['open sites','NO approaching','CO approaching'],micro:['NO','CO'],cap:'Blue atoms are nitrogen. This reaction is the reduction job in a three-way catalyst.'},
{title:'NO and CO adsorb',text:'NO binds and can separate into nitrogen and oxygen atoms. CO is held nearby, ready to take oxygen.',eq:'2 N* + 2 O* + 2 CO* on the surface',gas:[],surf:[['N*',2],['O*',2],['CO*',2]],prod:[],status:'Surface occupied: NO is dissociating',chips:['adsorbing NO','weakening N–O bonds','holding CO nearby','separating atoms'],micro:['N*','O*','CO*'],cap:'Surface nitrogen atoms can meet while surface oxygen reacts with CO.'},
{title:'N₂ and CO₂ form',text:'Two nitrogen atoms pair to make N₂. Each oxygen atom joins a CO molecule to make CO₂.',eq:'2 N* → N₂*; 2 CO* + 2 O* → 2 CO₂*',gas:[],surf:[['N2*',1],['CO2*',2]],prod:[],status:'Surface reaction: N₂ and CO₂ are forming',chips:['forming N≡N','transferring oxygen','oxidizing CO','reducing NO'],micro:['N2*','CO2*'],cap:'No atoms disappear: nitrogen pairs into N₂ and oxygen transfers from NO to CO.'},
{title:'N₂ and CO₂ leave',text:'N₂ and CO₂ detach. The rhodium-containing sites reopen and can process more NOₓ.',eq:'N₂* + 2 CO₂* → products + open sites',gas:[],surf:[],prod:[['N2',1],['CO2',2]],status:'Rh-containing surface: open again',chips:['desorbing products','restoring sites','ready to repeat'],micro:['N2','CO2'],cap:'N₂ is the stable nitrogen molecule that makes up most of ordinary air.'}]}
};
let reaction='co',step=0,cycles=0;
function clean(t){return t.replace('*','')}function formula(t){return F[clean(t)]||clean(t)}
function atom(l){return `<i class="atom ${l}">${l}</i>`}function art(t){t=clean(t);const b='<i class="bond"></i>';if(t==='CO')return atom('C')+b+atom('O');if(t==='O2')return atom('O')+b+atom('O');if(t==='O')return atom('O');if(t==='CO2')return atom('O')+b+atom('C')+b+atom('O');if(t==='H2O')return atom('H')+b+atom('O')+b+atom('H');if(t==='HC')return atom('C')+b+atom('C')+b+atom('C');if(t==='NO')return atom('N')+b+atom('O');if(t==='N')return atom('N');if(t==='N2')return atom('N')+b+atom('N');return ''}
function pill([t,n=1]){const bound=t.includes('*');return `<span class="mol${bound?' bound':''}" aria-label="${n>1?n+' molecules of ':''}${formula(t)}">${art(t)}<b>${formula(t)}${bound?'*':''}</b>${n>1?`<i class="count">×${n}</i>`:''}</span>`}
function put(id,list){document.getElementById(id).innerHTML=list.length?list.map(pill).join(''):'<span class="empty">No molecules in this region at this step.</span>'}
function rows(list,max){return list.map(([t,n,role])=>`<div class="bar-row"><span class="bar-label">${formula(t)}</span><span class="track" aria-hidden="true"><i class="fill ${role==='helper'?'helper':role==='product'?'product':''}" style="width:${Math.max(12,n/max*100)}%"></i></span><span class="bar-count">${n} molecule${n===1?'':'s'}</span></div>`).join('')}
function renderBalance(r){const max=Math.max(...r.before.map(x=>x[1]),...r.after.map(x=>x[1]));beforeGraph.innerHTML=rows(r.before,max);afterGraph.innerHTML=rows(r.after,max);const order=['C','H','N','O'];ledger.innerHTML=order.filter(a=>r.atoms[a]).map(a=>`<span><i class="${a}">${a}</i>${r.atoms[a]} in = ${r.atoms[a]} out</span>`).join('')+'<span><i style="background:var(--metal)">M</i>0 metal atoms in products</span>';balanceNote.textContent=r.balance}
function svgAtom(x,y,l){const colors={C:'#303943',O:'#d24f4f',N:'#2f6fa8',H:'#eef2f7'};const tc=l==='H'?'#344054':'#fff';return `<circle cx="${x}" cy="${y}" r="16" fill="${colors[l]}" stroke="rgba(0,0,0,.2)" stroke-width="2"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="${tc}" font-size="13" font-weight="900">${l}</text>`}
function svgMol(t,x,y){const c=clean(t),bound=t.includes('*');let atoms=[];if(c==='CO')atoms=['C','O'];else if(c==='O2')atoms=['O','O'];else if(c==='O')atoms=['O'];else if(c==='CO2')atoms=['O','C','O'];else if(c==='H2O')atoms=['H','O','H'];else if(c==='HC')atoms=['C','C','C'];else if(c==='NO')atoms=['N','O'];else if(c==='N')atoms=['N'];else if(c==='N2')atoms=['N','N'];const gap=34,start=x-(atoms.length-1)*gap/2;let s='';atoms.forEach((a,i)=>{if(i)s+=`<line x1="${start+(i-1)*gap+16}" y1="${y}" x2="${start+i*gap-16}" y2="${y}" stroke="#6d7782" stroke-width="4" stroke-linecap="round"/>`;s+=svgAtom(start+i*gap,y,a)});if(bound)s+=`<line x1="${x}" y1="${y+18}" x2="${x}" y2="230" stroke="#3d8f6b" stroke-width="3" stroke-dasharray="6 5"/>`;s+=`<text x="${x}" y="${y+34}" text-anchor="middle" fill="#465362" font-size="12" font-weight="850">${formula(t)}${bound?'*':''}</text>`;return s}
function renderMicro(d){let s='<defs><marker id="arrowhead" markerWidth="9" markerHeight="7" refX="8" refY="3.5" orient="auto"><polygon points="0 0,9 3.5,0 7" fill="#176b57"/></marker></defs>';[55,120,185,250,315,380,445].forEach(x=>s+=`<circle cx="${x}" cy="252" r="20" fill="#747f8a" stroke="rgba(0,0,0,.2)" stroke-width="2"/><text x="${x}" y="257" text-anchor="middle" fill="#fff" font-size="14" font-weight="900">M</text>`);s+='<rect x="24" y="242" width="452" height="42" rx="13" fill="rgba(116,127,138,.16)"/><text x="250" y="303" text-anchor="middle" fill="#55616f" font-size="13" font-weight="800">metal surface: Pt / Pd / Rh sites</text>';const items=d.micro;const xs=items.length===1?[250]:items.length===2?[155,345]:[110,250,390];const y=step===0?95:step===3?88:155;items.forEach((t,i)=>s+=svgMol(t,xs[i],y));if(step===0)s+='<line x1="250" y1="150" x2="250" y2="215" stroke="#176b57" stroke-width="4" marker-end="url(#arrowhead)"/><text x="250" y="185" text-anchor="middle" fill="#176b57" font-size="13" font-weight="850">approaching open sites</text>';if(step===1)s+='<text x="250" y="70" text-anchor="middle" fill="#176b57" font-size="13" font-weight="850">temporary bonds hold and activate reactants</text>';if(step===2)s+='<text x="250" y="70" text-anchor="middle" fill="#176b57" font-size="13" font-weight="850">existing atoms rearrange on neighboring sites</text>';if(step===3)s+='<line x1="250" y1="205" x2="250" y2="145" stroke="#176b57" stroke-width="4" marker-end="url(#arrowhead)"/><text x="250" y="210" text-anchor="middle" fill="#176b57" font-size="13" font-weight="850">products leave; sites reopen</text>';microSvg.innerHTML=s;microCaption.textContent=d.cap}
function updateEnergy(){const x=[58,154,258,398][step],w=[82,88,96,84][step];energyBand.setAttribute('x',x);energyBand.setAttribute('width',w);energyLabel.setAttribute('x',x+w/2);energyLabel.textContent=`STEP ${step+1}`;energyNote.textContent=energyNotes[step]}
function render(){const r=R[reaction],d=r.steps[step];stepKicker.textContent=`Step ${step+1} of 4 · ${r.name}`;stepTitle.textContent=d.title;stepText.textContent=d.text;overall.textContent=r.overall;stepEq.textContent=d.eq;surfaceStatus.textContent=d.status;impact.textContent=r.impact;productCaveat.textContent=r.caveat;chips.innerHTML=d.chips.map(x=>`<span class="chip">${x}</span>`).join('');progress.textContent=`Step ${step+1} of 4: ${stepNames[step].toLowerCase()}.`;put('gas',d.gas);put('surfaceMols',d.surf);put('products',d.prod);cyclesEl.textContent=cycles;const occupied=step===1||step===2;siteState.textContent=occupied?'Occupied':'Open';siteState.className=occupied?'occupied':'open';document.querySelectorAll('.tab').forEach(b=>{const a=b.dataset.reaction===reaction;b.setAttribute('aria-selected',a);b.tabIndex=a?0:-1});document.querySelectorAll('.step').forEach((b,i)=>{b.classList.toggle('active',i===step);b.classList.toggle('done',i<step);if(i===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});back.disabled=step===0;next.textContent=step===3?'Run another cycle ↻':'Next step →';beforeSide.classList.toggle('active',step<2);afterSide.classList.toggle('active',step>=2);renderMicro(d);updateEnergy()}
function setReaction(r){reaction=r;step=0;cycles=0;renderBalance(R[r]);render()}function advance(){if(step===3){cycles++;step=0}else step++;render()}function previous(){if(step>0){step--;render()}}function resetAll(){step=0;cycles=0;render()}
const cyclesEl=document.getElementById('cycles');document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setReaction(b.dataset.reaction)));document.querySelectorAll('.step').forEach(b=>b.addEventListener('click',()=>{step=+b.dataset.step;render()}));next.addEventListener('click',advance);back.addEventListener('click',previous);reset.addEventListener('click',resetAll);document.addEventListener('keydown',e=>{if(e.target.matches('button,input,textarea,select,summary'))return;if(e.key==='ArrowRight'){e.preventDefault();advance()}if(e.key==='ArrowLeft'){e.preventDefault();previous()}if(e.key.toLowerCase()==='r'){e.preventDefault();resetAll()}});document.querySelectorAll('.quiz-options button').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.answer==='correct';document.querySelectorAll('.quiz-options button').forEach(x=>{x.disabled=true;if(x.dataset.answer==='correct')x.classList.add('correct')});if(!ok)b.classList.add('wrong');feedback.textContent=ok?'Correct. The surface lowers the barrier and returns to a usable state.':'Not quite. The metal is not added to products; it provides a lower-barrier pathway and is regenerated.'}));renderBalance(R[reaction]);render();
